apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cids-auth

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - certificate.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: cids-auth
  app.kubernetes.io/version: "2.0.0"
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/jnbaileyiv-cto/cids-2
    newTag: latest  # Update with specific version for production