apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cids-auth-data
  namespace: cids-auth
  labels:
    app.kubernetes.io/name: cids-auth
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path  # Adjust for your cluster